import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/source-sans-pro";

export const metadata: Metadata = {
  title: "CirCre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-[SourceSansPro] antialiased text-[#3D3935]">
        {children}
      </body>
    </html>
  );
}
